//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnotationWhitelist) DeepCopyInto(out *AnnotationWhitelist) {
	*out = *in
	if in.ContainerSpec != nil {
		in, out := &in.ContainerSpec, &out.ContainerSpec
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.WorkloadController != nil {
		in, out := &in.WorkloadController, &out.WorkloadController
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotationWhitelist.
func (in *AnnotationWhitelist) DeepCopy() *AnnotationWhitelist {
	if in == nil {
		return nil
	}
	out := new(AnnotationWhitelist)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaemonPodDetectors) DeepCopyInto(out *DaemonPodDetectors) {
	*out = *in
	if in.PodNamePatterns != nil {
		in, out := &in.PodNamePatterns, &out.PodNamePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespacePatterns != nil {
		in, out := &in.NamespacePatterns, &out.NamespacePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaemonPodDetectors.
func (in *DaemonPodDetectors) DeepCopy() *DaemonPodDetectors {
	if in == nil {
		return nil
	}
	out := new(DaemonPodDetectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Discovery) DeepCopyInto(out *Discovery) {
	*out = *in
	if in.ChunkSendDelayMillis != nil {
		in, out := &in.ChunkSendDelayMillis, &out.ChunkSendDelayMillis
		*out = new(int32)
		**out = **in
	}
	if in.NumObjectsPerChunk != nil {
		in, out := &in.NumObjectsPerChunk, &out.NumObjectsPerChunk
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Discovery.
func (in *Discovery) DeepCopy() *Discovery {
	if in == nil {
		return nil
	}
	out := new(Discovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExclusionDetectors) DeepCopyInto(out *ExclusionDetectors) {
	*out = *in
	if in.OperatorControlledWorkloadsPatterns != nil {
		in, out := &in.OperatorControlledWorkloadsPatterns, &out.OperatorControlledWorkloadsPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OperatorControlledNamespacePatterns != nil {
		in, out := &in.OperatorControlledNamespacePatterns, &out.OperatorControlledNamespacePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExclusionDetectors.
func (in *ExclusionDetectors) DeepCopy() *ExclusionDetectors {
	if in == nil {
		return nil
	}
	out := new(ExclusionDetectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubeturbo) DeepCopyInto(out *Kubeturbo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubeturbo.
func (in *Kubeturbo) DeepCopy() *Kubeturbo {
	if in == nil {
		return nil
	}
	out := new(Kubeturbo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kubeturbo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeturboArgs) DeepCopyInto(out *KubeturboArgs) {
	*out = *in
	if in.Logginglevel != nil {
		in, out := &in.Logginglevel, &out.Logginglevel
		*out = new(int)
		**out = **in
	}
	if in.Kubelethttps != nil {
		in, out := &in.Kubelethttps, &out.Kubelethttps
		*out = new(bool)
		**out = **in
	}
	if in.Kubeletport != nil {
		in, out := &in.Kubeletport, &out.Kubeletport
		*out = new(int)
		**out = **in
	}
	if in.Sccsupport != nil {
		in, out := &in.Sccsupport, &out.Sccsupport
		*out = new(string)
		**out = **in
	}
	if in.ReadinessRetryThreshold != nil {
		in, out := &in.ReadinessRetryThreshold, &out.ReadinessRetryThreshold
		*out = new(int32)
		**out = **in
	}
	if in.FailVolumePodMoves != nil {
		in, out := &in.FailVolumePodMoves, &out.FailVolumePodMoves
		*out = new(bool)
		**out = **in
	}
	if in.BusyboxExcludeNodeLabels != nil {
		in, out := &in.BusyboxExcludeNodeLabels, &out.BusyboxExcludeNodeLabels
		*out = new(string)
		**out = **in
	}
	if in.Stitchuuid != nil {
		in, out := &in.Stitchuuid, &out.Stitchuuid
		*out = new(bool)
		**out = **in
	}
	if in.Pre16K8sVersion != nil {
		in, out := &in.Pre16K8sVersion, &out.Pre16K8sVersion
		*out = new(bool)
		**out = **in
	}
	if in.CleanupSccImpersonationResources != nil {
		in, out := &in.CleanupSccImpersonationResources, &out.CleanupSccImpersonationResources
		*out = new(bool)
		**out = **in
	}
	if in.SkipCreatingSccImpersonationResources != nil {
		in, out := &in.SkipCreatingSccImpersonationResources, &out.SkipCreatingSccImpersonationResources
		*out = new(bool)
		**out = **in
	}
	if in.GitEmail != nil {
		in, out := &in.GitEmail, &out.GitEmail
		*out = new(string)
		**out = **in
	}
	if in.GitUsername != nil {
		in, out := &in.GitUsername, &out.GitUsername
		*out = new(string)
		**out = **in
	}
	if in.GitSecretName != nil {
		in, out := &in.GitSecretName, &out.GitSecretName
		*out = new(string)
		**out = **in
	}
	if in.GitSecretNamespace != nil {
		in, out := &in.GitSecretNamespace, &out.GitSecretNamespace
		*out = new(string)
		**out = **in
	}
	if in.GitCommitMode != nil {
		in, out := &in.GitCommitMode, &out.GitCommitMode
		*out = new(string)
		**out = **in
	}
	if in.SatelliteLocationProvider != nil {
		in, out := &in.SatelliteLocationProvider, &out.SatelliteLocationProvider
		*out = new(string)
		**out = **in
	}
	if in.DiscoveryIntervalSec != nil {
		in, out := &in.DiscoveryIntervalSec, &out.DiscoveryIntervalSec
		*out = new(int)
		**out = **in
	}
	if in.DiscoverySampleIntervalSec != nil {
		in, out := &in.DiscoverySampleIntervalSec, &out.DiscoverySampleIntervalSec
		*out = new(int)
		**out = **in
	}
	if in.DiscoverySamples != nil {
		in, out := &in.DiscoverySamples, &out.DiscoverySamples
		*out = new(int)
		**out = **in
	}
	if in.DiscoveryTimeoutSec != nil {
		in, out := &in.DiscoveryTimeoutSec, &out.DiscoveryTimeoutSec
		*out = new(int)
		**out = **in
	}
	if in.GarbageCollectionIntervalMin != nil {
		in, out := &in.GarbageCollectionIntervalMin, &out.GarbageCollectionIntervalMin
		*out = new(int)
		**out = **in
	}
	if in.DiscoveryWorkers != nil {
		in, out := &in.DiscoveryWorkers, &out.DiscoveryWorkers
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeturboArgs.
func (in *KubeturboArgs) DeepCopy() *KubeturboArgs {
	if in == nil {
		return nil
	}
	out := new(KubeturboArgs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeturboHANodeConfig) DeepCopyInto(out *KubeturboHANodeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeturboHANodeConfig.
func (in *KubeturboHANodeConfig) DeepCopy() *KubeturboHANodeConfig {
	if in == nil {
		return nil
	}
	out := new(KubeturboHANodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeturboImage) DeepCopyInto(out *KubeturboImage) {
	*out = *in
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
	if in.BusyboxRepository != nil {
		in, out := &in.BusyboxRepository, &out.BusyboxRepository
		*out = new(string)
		**out = **in
	}
	if in.CpufreqgetterRepository != nil {
		in, out := &in.CpufreqgetterRepository, &out.CpufreqgetterRepository
		*out = new(string)
		**out = **in
	}
	if in.PullPolicy != nil {
		in, out := &in.PullPolicy, &out.PullPolicy
		*out = new(corev1.PullPolicy)
		**out = **in
	}
	if in.ImagePullSecret != nil {
		in, out := &in.ImagePullSecret, &out.ImagePullSecret
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeturboImage.
func (in *KubeturboImage) DeepCopy() *KubeturboImage {
	if in == nil {
		return nil
	}
	out := new(KubeturboImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeturboList) DeepCopyInto(out *KubeturboList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kubeturbo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeturboList.
func (in *KubeturboList) DeepCopy() *KubeturboList {
	if in == nil {
		return nil
	}
	out := new(KubeturboList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeturboList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeturboPodScheduling) DeepCopyInto(out *KubeturboPodScheduling) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeturboPodScheduling.
func (in *KubeturboPodScheduling) DeepCopy() *KubeturboPodScheduling {
	if in == nil {
		return nil
	}
	out := new(KubeturboPodScheduling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeturboRestAPIConfig) DeepCopyInto(out *KubeturboRestAPIConfig) {
	*out = *in
	if in.OpsManagerUserName != nil {
		in, out := &in.OpsManagerUserName, &out.OpsManagerUserName
		*out = new(string)
		**out = **in
	}
	if in.OpsManagerPassword != nil {
		in, out := &in.OpsManagerPassword, &out.OpsManagerPassword
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeturboRestAPIConfig.
func (in *KubeturboRestAPIConfig) DeepCopy() *KubeturboRestAPIConfig {
	if in == nil {
		return nil
	}
	out := new(KubeturboRestAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeturboSdkProtocolConfig) DeepCopyInto(out *KubeturboSdkProtocolConfig) {
	*out = *in
	if in.RegistrationTimeoutSec != nil {
		in, out := &in.RegistrationTimeoutSec, &out.RegistrationTimeoutSec
		*out = new(int)
		**out = **in
	}
	if in.RestartOnRegistrationTimeout != nil {
		in, out := &in.RestartOnRegistrationTimeout, &out.RestartOnRegistrationTimeout
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeturboSdkProtocolConfig.
func (in *KubeturboSdkProtocolConfig) DeepCopy() *KubeturboSdkProtocolConfig {
	if in == nil {
		return nil
	}
	out := new(KubeturboSdkProtocolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeturboServerMeta) DeepCopyInto(out *KubeturboServerMeta) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeturboServerMeta.
func (in *KubeturboServerMeta) DeepCopy() *KubeturboServerMeta {
	if in == nil {
		return nil
	}
	out := new(KubeturboServerMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeturboSpec) DeepCopyInto(out *KubeturboSpec) {
	*out = *in
	in.DaemonPodDetectors.DeepCopyInto(&out.DaemonPodDetectors)
	in.AnnotationWhitelist.DeepCopyInto(&out.AnnotationWhitelist)
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	in.Image.DeepCopyInto(&out.Image)
	in.ServerMeta.DeepCopyInto(&out.ServerMeta)
	in.RestAPIConfig.DeepCopyInto(&out.RestAPIConfig)
	in.SdkProtocolConfig.DeepCopyInto(&out.SdkProtocolConfig)
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.HANodeConfig = in.HANodeConfig
	in.TargetConfig.DeepCopyInto(&out.TargetConfig)
	in.Args.DeepCopyInto(&out.Args)
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	in.Logging.DeepCopyInto(&out.Logging)
	in.NodePoolSize.DeepCopyInto(&out.NodePoolSize)
	in.OrmOwners.DeepCopyInto(&out.OrmOwners)
	in.SystemWorkloadDetectors.DeepCopyInto(&out.SystemWorkloadDetectors)
	in.ExclusionDetectors.DeepCopyInto(&out.ExclusionDetectors)
	in.Wiremock.DeepCopyInto(&out.Wiremock)
	in.Discovery.DeepCopyInto(&out.Discovery)
	in.KubeturboPodScheduling.DeepCopyInto(&out.KubeturboPodScheduling)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeturboSpec.
func (in *KubeturboSpec) DeepCopy() *KubeturboSpec {
	if in == nil {
		return nil
	}
	out := new(KubeturboSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeturboStatus) DeepCopyInto(out *KubeturboStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeturboStatus.
func (in *KubeturboStatus) DeepCopy() *KubeturboStatus {
	if in == nil {
		return nil
	}
	out := new(KubeturboStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeturboTargetConfig) DeepCopyInto(out *KubeturboTargetConfig) {
	*out = *in
	if in.TargetName != nil {
		in, out := &in.TargetName, &out.TargetName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeturboTargetConfig.
func (in *KubeturboTargetConfig) DeepCopy() *KubeturboTargetConfig {
	if in == nil {
		return nil
	}
	out := new(KubeturboTargetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Logging) DeepCopyInto(out *Logging) {
	*out = *in
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging.
func (in *Logging) DeepCopy() *Logging {
	if in == nil {
		return nil
	}
	out := new(Logging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolSize) DeepCopyInto(out *NodePoolSize) {
	*out = *in
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		*out = new(int)
		**out = **in
	}
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolSize.
func (in *NodePoolSize) DeepCopy() *NodePoolSize {
	if in == nil {
		return nil
	}
	out := new(NodePoolSize)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrmOwners) DeepCopyInto(out *OrmOwners) {
	*out = *in
	if in.ApiGroup != nil {
		in, out := &in.ApiGroup, &out.ApiGroup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrmOwners.
func (in *OrmOwners) DeepCopy() *OrmOwners {
	if in == nil {
		return nil
	}
	out := new(OrmOwners)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(map[corev1.ResourceName]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemWorkloadDetectors) DeepCopyInto(out *SystemWorkloadDetectors) {
	*out = *in
	if in.NamespacePatterns != nil {
		in, out := &in.NamespacePatterns, &out.NamespacePatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemWorkloadDetectors.
func (in *SystemWorkloadDetectors) DeepCopy() *SystemWorkloadDetectors {
	if in == nil {
		return nil
	}
	out := new(SystemWorkloadDetectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wiremock) DeepCopyInto(out *Wiremock) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wiremock.
func (in *Wiremock) DeepCopy() *Wiremock {
	if in == nil {
		return nil
	}
	out := new(Wiremock)
	in.DeepCopyInto(out)
	return out
}
