apiVersion: v1
kind: Service
metadata:
  labels:
    name: kubeturbo-operator
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: kubeturbo-operator-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: kubeturbo-deploy
    app.kubernetes.io/part-of: kubeturbo-deploy
    app.kubernetes.io/managed-by: kustomize
  name: kubeturbo-operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    name: kubeturbo-operator
