apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: kubeturbo-operator-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeturbo-deploy
    app.kubernetes.io/part-of: kubeturbo-deploy
    app.kubernetes.io/managed-by: kustomize
  name: kubeturbo-operator
  namespace: system
