apiVersion: v1
kind: Namespace
metadata:
  # turbo is default value used in the samples provided
  name: turbo
---
apiVersion: v1
kind: Secret
metadata:
  name: turbonomic-credentials
  namespace: turbo
type: Opaque
data:
  # username: <Username_encoded_base64>
  # password: <Password_encoded_base64>
  clientid: <Client_id_encoded_base64>
  clientsecret: <Client_secret_encoded_base64>
---
